# Standard port for Eureka
server:
  port: 8761

eureka:
  instance:
    # Network card to use
    hostname: localhost
  client:
    # Don't record itself
    registerWithEureka: false
    # Client doesn't cache registry
    fetchRegistry: false
